from pathlib import Path
from ..tools.fs_tools import write_file
from .product_manager import Plan


BACKEND_README = """# Backend Overview

Generated by the **AI Dev Team**.

Suggested backend tech stack:

{tech_stack}

Backend features planned:

{features_list}
"""


def implement_backend_skeleton(plan: Plan, project_root: str) -> list[str]:
    created = []

    # Ensure project_root is a Path object
    project_root = Path(project_root)

    # Backend folder → projects/<name>/backend
    backend_path = project_root / "backend"
    app_path_dir = backend_path / "app"
    app_path_dir.mkdir(parents=True, exist_ok=True)

    # -------- README --------
    backend_features = [
        f"- ({f.priority}) {f.title}: {f.description}"
        for f in plan.features if f.area == "backend"
    ]

    features_list = "\n".join(backend_features) or "No backend features included."
    tech_stack_list = "\n".join(f"- {t}" for t in plan.tech_stack)

    readme_path = backend_path / "README.md"
    write_file(
        str(readme_path),
        BACKEND_README.format(
            tech_stack=tech_stack_list,
            features_list=features_list,
        )
    )
    created.append(str(readme_path))

    # -------- app/main.py (FastAPI starter) --------
    main_py = f"""
from fastapi import FastAPI

app = FastAPI(title="AI Generated Backend – {plan.project_name}")

@app.get("/health")
async def health():
    return {{"status": "ok", "service": "{plan.project_name}"}}
"""
    main_file_path = app_path_dir / "main.py"
    write_file(str(main_file_path), main_py)
    created.append(str(main_file_path))

    # -------- requirements.txt --------
    requirements = """fastapi
uvicorn
"""
    req_path = backend_path / "requirements.txt"
    write_file(str(req_path), requirements)
    created.append(str(req_path))

    return created
