from .product_manager import Plan
from ..tools.fs_tools import write_file
from pathlib import Path
import os


FRONTEND_README = """# Frontend Overview

This frontend is generated by the **AI Dev Team**.
It is meant as a starting point.

## Tech stack (suggested)

- React or Next.js
- TypeScript (optional but recommended)
- Tailwind CSS

AI suggested frontend features:

{features_list}
"""


def implement_frontend_skeleton(plan: Plan, project_root: str) -> list[str]:
    created = []

    # Convert to Path object (FIX)
    project_root = Path(project_root)

    frontend_path = project_root / "frontend"
    src_path = frontend_path / "src"

    os.makedirs(src_path, exist_ok=True)

    # -------- README --------
    frontend_features = [
        f"- ({f.priority}) {f.title}: {f.description}"
        for f in plan.features if f.area == "frontend"
    ]

    features_list = "\n".join(frontend_features) or "No frontend features included."

    readme_path = frontend_path / "README.md"
    write_file(str(readme_path), FRONTEND_README.format(features_list=features_list))
    created.append(str(readme_path))

    # -------- App.jsx --------
    app_jsx = f"""
import React from "react";

export default function App() {{
  return (
    <div className="p-8 font-sans">
      <h1 className="text-3xl font-bold mb-4">
        AI Generated Frontend Shell – {plan.project_name}
      </h1>
      <p className="text-gray-700">
        This is a minimal placeholder. Follow the project plan and implement
        real pages, routes, and components.
      </p>
    </div>
  );
}}
"""
    app_path = src_path / "App.jsx"
    write_file(str(app_path), app_jsx)
    created.append(str(app_path))

    # -------- package.json --------
    pkg_json = f"""
{{
  "name": "{plan.project_name.lower().replace(" ", "-")}-frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  }},
  "dependencies": {{
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  }},
  "devDependencies": {{
    "@vitejs/plugin-react": "^4.0.0",
    "vite": "^6.0.0"
  }}
}}
"""
    pkg_path = frontend_path / "package.json"
    write_file(str(pkg_path), pkg_json)
    created.append(str(pkg_path))

    # -------- vite.config.mjs --------
    vite_config = """
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});
"""
    vite_path = frontend_path / "vite.config.mjs"
    write_file(str(vite_path), vite_config)
    created.append(str(vite_path))

    return created
