from .product_manager import Plan
from ..tools.fs_tools import write_file
import os


BACKEND_README = """# Backend Overview

Generated by the **AI Dev Team**.

Suggested backend tech stack:

{tech_stack}

Backend features planned:

{features_list}
"""


def generate_test_notes(plan: Plan, project_name: str) -> list[str]:
    path = f"{project_name}/TESTING_NOTES.md"
    content = f"""\
# Testing Notes (AI Generated)

This document is a starting point for test strategy.

Project: {plan.project_name}

High-level recommended tests:

- Unit tests for core business logic
- API tests for critical endpoints
- Basic UI smoke tests
- Authentication & authorization tests (if relevant)
- Performance tests for key flows (optional at early stage)

You should refine this document and add concrete test plans, tools, and coverage goals.
"""
    write_file(path, content)
    return [path]


def implement_backend_skeleton(plan: Plan, project_root: str) -> list[str]:
    created = []

    backend_path = f"{project_root}/backend"
    os.makedirs(f"{backend_path}/app", exist_ok=True)

    # -------- README --------
    backend_features = [
        f"- ({f.priority}) {f.title}: {f.description}"
        for f in plan.features if f.area == "backend"
    ]

    features_list = "\n".join(backend_features) or "No backend features included."
    tech_stack = "\n".join(f"- {t}" for t in plan.tech_stack)

    readme_path = f"{backend_path}/README.md"
    write_file(readme_path, BACKEND_README.format(
        tech_stack=tech_stack,
        features_list=features_list
    ))
    created.append(readme_path)

    # -------- app/main.py (FastAPI starter) --------
    app_file = f"""
from fastapi import FastAPI

app = FastAPI(title="AI Generated Backend – {plan.project_name}")

@app.get("/health")
async def health():
    return {{"status": "ok", "service": "{plan.project_name}"}}
"""
    app_path = f"{backend_path}/app/main.py"
    write_file(app_path, app_file)
    created.append(app_path)

    # -------- requirements.txt --------
    reqs = """
fastapi
uvicorn
"""
    req_path = f"{backend_path}/requirements.txt"
    write_file(req_path, reqs)
    created.append(req_path)

    return created
